const ALERT_SHOW_TIME = 5000;

const CONTROL_MAX_VALUE = 100;
const CONTROL_MIN_VALUE = 25;
const CONTROL_STEP = 25;
const CONTROL_DEFAULT_VALUE = 100;

const EFFECT_CLASS_START = 'effects__preview--';

const HASHTAGS_DELIMITER = ' ';
const HASHTAGS_MAX_COUNT = 5;
const DESCRIPTION_MAX_LENGTH = 140;

const RECEIVE_DATA_URL = 'https://22.javascript.pages.academy/kekstagram/data';
const SEND_DATA_URL = 'https://22.javascript.pages.academy/kekstagram';

export {
  ALERT_SHOW_TIME,
  CONTROL_MAX_VALUE,
  CONTROL_MIN_VALUE,
  CONTROL_STEP,
  CONTROL_DEFAULT_VALUE,
  EFFECT_CLASS_START,
  HASHTAGS_DELIMITER,
  HASHTAGS_MAX_COUNT,
  DESCRIPTION_MAX_LENGTH,
  RECEIVE_DATA_URL,
  SEND_DATA_URL
};
